name: C/C++  SAST with cppcheck

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cpp-check:

    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: cppcheck
      run: cppcheck -i config/tests --quiet .
